# f string formating

In [ ]:
# f string - New after python 3.6
name = "Juned Ansari"
print(f"My Name is {name}")

mydict = {
    'name':'Juned Ansari',
    'age':33
}

print(f"My Name is {mydict['name']} and Age: {mydict['age']}")

print("\n")
# formating using f string
library = {
    ('Author','Topic','Pages'),
    ('Abc','History',1200),
    ('xyz','Geography',300),
    ('pqr','Math',200)
}

# Before Formating
print("Before Formating:")
for author,topic,pages in library:
    print(f"{author} {topic} {pages}")

print("\n")
print("After Formating:")
# After Formating
for author,topic,pages in library:
    print(f"{author:{10}} {topic:{20}} {pages:{5}}")

My Name is Juned Ansari
My Name is Juned Ansari and Age: 33


Before Formating:
xyz Geography 300
pqr Math 200
Author Topic Pages
Abc History 1200


After Formating:
xyz        Geography              300
pqr        Math                   200
Author     Topic                Pages
Abc        History               1200


# Working with Text File

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
%%writefile sample.txt
This is sample text file
my name is juned ansari
i am a data scientist
my qualification is mscit.

Writing sample.txt


In [ ]:
#Read File
file = open("sample.txt")
for line in file.readlines():
  print(line)

This is sample text file 

my name is juned ansari 

i am a data scientist

my qualification is mscit.


In [ ]:
# Append file
file = open("sample.txt","a+")
file.write("New Line Appended")
file.close()

myfile = open("sample.txt")
print(myfile.read())

This is sample text file 
my name is juned ansari 
i am a data scientist
my qualification is mscit.New Line Appended


In [ ]:
myfile.seek(0)
content = myfile.readlines()
for line in content:
    print(line)
myfile.close()

This is sample text file 

my name is juned ansari 

i am a data scientist

my qualification is mscit.New Line Appended


# Working Regular Expression

In [ ]:
import re
text = "Hello india My Mobile Number is 990-477-3679 and roll number is 03"
pattern = '(\d{3})-(\d{3})-(\d{4})'
print(re.search(pattern,text).group())
print(re.search(pattern,text).group(1))
print(re.search(pattern,text).group(2))
print(re.search(pattern,text).group(3))

990-477-3679
990
477
3679


In [ ]:
for data in re.findall(pattern,text):
  print(data)

('990', '477', '3679')


In [ ]:
print(re.search("Apple|Mango","I like Apple and Mango").group())

Apple


In [ ]:
print(re.findall("Apple|Mango","I like Apple and Mango"))

['Apple', 'Mango']


# Working with Spacy

**Tokenization**

In [ ]:
#Import the English Language Class
import spacy
nlp = spacy.load('en_core_web_sm')
doc = nlp("Hello World, A 5km cab ride to cost $10")
for token in doc:
  print(token.text)

#To Display Dependency
from spacy import displacy
doc = nlp(u'Apple is going to build a U.K. factory for $6 million.')
displacy.render(doc, style='dep', jupyter=True, options={'distance': 110})

#To Display Entity
print("Entity Display:")
displacy.render(doc, style='ent', jupyter=True, options={'distance': 110})

Hello
World
,
A
5
km
cab
ride
to
cost
$
10


Entity Display:


In [ ]:
import spacy
nlp = spacy.load('en_core_web_sm')
doc = nlp(u"It cost $5 million and Companies Email is ansarijuned4all@gmail.com and i live in india, right now I am eating mango")
print("Sentence Token:", [sentense for sentense in doc.sents])
# Sentence Token: [It cost $5 million and Companies Email is ansarijuned4all@gmail.com, and i live in india, , right now I am eating mango]
print("Token:", [token.text for token in doc])
# Token: ['It', 'cost', '$', '5', 'million', 'and', 'Companies', 'Email', 'is', 'ansarijuned4all@gmail.com', 'and', 'i', 'live', 'in', 'india', ',', 'right', 'now', 'I', 'am', 'eating', 'mango']
print("Token Index:", [token.i for token in doc])
# Token Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
print("\n")
print("Named Entity Recongnisation(NER):")
for token in doc.ents:
  print(token.text,":::Label(N E R):::",token.label_,"::: Explain:::",spacy.explain(token.label_))
"""
Named Entity Recongnisation(NER):
$5 million :::Label(N E R)::: MONEY ::: Explain::: Monetary values, including unit
Companies Email :::Label(N E R)::: ORG ::: Explain::: Companies, agencies, institutions, etc.
ansarijuned4all@gmail.com :::Label(N E R)::: ORG ::: Explain::: Companies, agencies, institutions, etc.
india :::Label(N E R)::: GPE ::: Explain::: Countries, cities, states
"""
print("\n")
print("POS_:",[token.pos_ for token in doc])
# POS_: ['PRON', 'VERB', 'SYM', 'NUM', 'NUM', 'CCONJ', 'PROPN', 'PROPN', 'AUX', 'X', 'CCONJ', 'PRON', 'VERB', 'ADP', 'PROPN', 'PUNCT', 'ADV', 'ADV', 'PRON', 'AUX', 'VERB', 'NOUN']
print("tag_:",[token.tag_ for token in doc])
# tag_: ['PRP', 'VBD', '$', 'CD', 'CD', 'CC', 'NNPS', 'NNP', 'VBZ', 'ADD', 'CC', 'PRP', 'VBP', 'IN', 'NNP', ',', 'RB', 'RB', 'PRP', 'VBP', 'VBG', 'NN']
print("tag_:",[spacy.explain(token.tag_) for token in doc])
# tag_: ['pronoun, personal', 'verb, past tense', 'symbol, currency', 'cardinal number', 'cardinal number', 'conjunction, coordinating', 'noun, proper plural', 'noun, proper singular', 'verb, 3rd person singular present', 'email', 'conjunction, coordinating', 'pronoun, personal', 'verb, non-3rd person singular present', 'conjunction, subordinating or preposition', 'noun, proper singular', 'punctuation mark, comma', 'adverb', 'adverb', 'pronoun, personal', 'verb, non-3rd person singular present', 'verb, gerund or present participle', 'noun, singular or mass']
print("lemma_:",[token.lemma_ for token in doc])
# lemma_: ['-PRON-', 'cost', '$', '5', 'million', 'and', 'Companies', 'Email', 'be', 'ansarijuned4all@gmail.com', 'and', 'i', 'live', 'in', 'india', ',', 'right', 'now', '-PRON-', 'be', 'eat', 'mango']
print("is_stop:",[token.is_stop for token in doc])
# is_stop: [True, False, False, False, False, True, False, False, True, False, True, True, False, True, False, False, False, True, True, True, False, False]
print("is_alpha:", [token.is_alpha for token in doc])
# is_alpha: [True, True, False, False, True, True, True, True, True, False, True, True, True, True, True, False, True, True, True, True, True, True]
print("is_punct:", [token.is_punct for token in doc])
# is_punct: [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False]
print("like_num:", [token.like_num for token in doc])
# like_num: [False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
print("like_email:", [token.like_email for token in doc])
# like_email: [False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False]
print("doc.ents Length:",len(doc.ents))
#doc.ents Length: 4


Sentence Token: [It cost $5 million and Companies Email is ansarijuned4all@gmail.com, and i live in india, , right now I am eating mango]
Token: ['It', 'cost', '$', '5', 'million', 'and', 'Companies', 'Email', 'is', 'ansarijuned4all@gmail.com', 'and', 'i', 'live', 'in', 'india', ',', 'right', 'now', 'I', 'am', 'eating', 'mango']
Token Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]


Named Entity Recongnisation(NER):
$5 million :::Label(N E R)::: MONEY ::: Explain::: Monetary values, including unit
Companies Email :::Label(N E R)::: ORG ::: Explain::: Companies, agencies, institutions, etc.
ansarijuned4all@gmail.com :::Label(N E R)::: ORG ::: Explain::: Companies, agencies, institutions, etc.
india :::Label(N E R)::: GPE ::: Explain::: Countries, cities, states


Chunks:
It
Companies Email
i
india
I
mango


POS_: ['PRON', 'VERB', 'SYM', 'NUM', 'NUM', 'CCONJ', 'PROPN', 'PROPN', 'AUX', 'X', 'CCONJ', 'PRON', 'VERB', 'ADP', 'PROPN', 'PUNCT', 'ADV', 'AD

**Stemming**

In [ ]:
# Stemming is not a part of Spacy, it is part of NLTK
import nltk
from nltk.stem.porter import PorterStemmer
p_stemmer = PorterStemmer()
words = ['run','running','ran','runs','runner','easily','fairly']
for word in words:
  print(word,"----->",p_stemmer.stem(word))

run -----> run
running -----> run
ran -----> ran
runs -----> run
runner -----> runner
easily -----> easili
fairly -----> fairli


***Lemmatization***

In [ ]:
doc = nlp(u'Tesla is looking to buy U.S based startup company for $6 million')
for token in doc:
  print("Token:", token, "      POS_=> " ,token.pos_ , "    lemma_=> ", token.lemma_, "     dep_=> ", token.dep_)

Token: Tesla       POS_=>  PROPN     lemma_=>  Tesla      dep_=>  nsubj
Token: is       POS_=>  AUX     lemma_=>  be      dep_=>  aux
Token: looking       POS_=>  VERB     lemma_=>  look      dep_=>  ROOT
Token: to       POS_=>  PART     lemma_=>  to      dep_=>  aux
Token: buy       POS_=>  VERB     lemma_=>  buy      dep_=>  xcomp
Token: U.S       POS_=>  PROPN     lemma_=>  U.S      dep_=>  npadvmod
Token: based       POS_=>  VERB     lemma_=>  base      dep_=>  amod
Token: startup       POS_=>  PROPN     lemma_=>  startup      dep_=>  compound
Token: company       POS_=>  NOUN     lemma_=>  company      dep_=>  dobj
Token: for       POS_=>  ADP     lemma_=>  for      dep_=>  prep
Token: $       POS_=>  SYM     lemma_=>  $      dep_=>  quantmod
Token: 6       POS_=>  NUM     lemma_=>  6      dep_=>  compound
Token: million       POS_=>  NUM     lemma_=>  million      dep_=>  pobj


***Stop Words***

In [ ]:
#Import the English Language Class
import spacy

from spacy.lang.en import English
# Load English tokenizer, tagger, parser, NER and word vectors
nlp = English()


# import nltk
# nltk.download("stopwords")

from spacy.lang.en.stop_words import STOP_WORDS

In [ ]:
# list of stopwords in english language
print(nlp.Defaults.stop_words)

{'me', 'hundred', 'both', 'down', 'although', 'herself', 'during', 'somehow', 'there', 'who', 'regarding', 'almost', 'now', 'ten', 'these', 'he', 'everywhere', 'any', 'done', 'above', 'no', 'part', 'nobody', 'doing', '‘re', 'anyhow', 'either', 'wherein', 'an', 'on', 'however', 'could', 'whither', 'with', 'thereafter', 'ourselves', 'much', 'yet', 'whatever', 'used', "'m", 'myself', 'beside', 'eleven', 'further', 'whence', 'already', 'seem', 'five', 'mostly', 'top', 'whole', 'yourselves', 'can', 'and', 'herein', 'meanwhile', 'sometimes', 'their', 'most', 'beforehand', 'do', 'full', 'several', 'call', 'those', 'whereas', 'due', 'cannot', 'have', "n't", 'anywhere', 'twelve', 'whom', 'put', 'over', 'four', 'seemed', 'the', "'d", 'something', 'by', '’re', 'one', 'latterly', 'back', 'except', '’m', 'someone', 'your', 'move', 'as', 'becomes', 'became', 'its', 'of', 'onto', 'after', 'seems', 'anyway', 'than', 'few', 'say', 'below', 'whereupon', 'towards', 'enough', 'nevertheless', 'therein', 'n

In [ ]:
# how to check whether any word is stopwords or not
print(nlp.vocab['via'].is_stop)
print(nlp.vocab['india'].is_stop)
print(nlp.vocab['testing'].is_stop)

True
False
False


In [ ]:
# to add any non-stopword into stop word list
nlp.Defaults.stop_words.add('testing')
# set the stopword tag on the lexeme
nlp.vocab['testing'].is_stop = True
print(nlp.vocab['testing'].is_stop)

True


In [ ]:
# to remove any non-stopword into stop word list
nlp.Defaults.stop_words.remove('testing')
# remove the stopword tag on the lexeme
nlp.vocab['testing'].is_stop = False
print(nlp.vocab['testing'].is_stop)

False


In [ ]:
# Filterout non-stopwords from the doc.
import spacy
from spacy.lang.en import English
nlp = English()
from spacy.lang.en.stop_words import STOP_WORDS
doc = nlp('Hello World, I am Juned')
for word in doc:
    if(str(word).lower() not in STOP_WORDS):
      print(word,":",word.is_stop)


Hello : False
World : False
, : False
Juned : False


**NER(Named Entity Recognision)**

In [ ]:
# we can also add out custom entity to NER
doc = nlp(u"It cost $5 millions and Companies Email is ansarijuned4all@gmail.com and i live in india, right now I am eating mango")
for token in doc.ents:
  print("Entity:",token.text)
  print("Label:",token.label_)
  print("Explain:",spacy.explain(token.label_))
  print("\n")


In [ ]:
list(doc.ents)

[]

In [ ]:
from spacy import displacy
displacy.render(doc, style='ent', jupyter=True)

/usr/lib/python3.6/runpy.py:193: UserWarning: [W006] No entities to visualize found in Doc object. If this is surprising to you, make sure the Doc was processed using a model that supports named entity recognition, and check the `doc.ents` property manually if necessary.
  "__main__", mod_spec)


In [ ]:
# Add custom entity to NER
doc = nlp(u"Tesla to build a U.K Factory for $6 million.")
list(doc.ents)
# here tesla should be identified as ORG but spacy could't so lets see how to add

[]

In [ ]:
from spacy.tokens import Span
ORG = doc.vocab.strings[u"ORG"]
print(ORG)
new_entity = Span(doc,0,1,label=ORG)
doc.ents = list(doc.ents) + [new_entity]
print(list(doc.ents)) # Now Tesla is identified as ORG

383
[Tesla]


**Chunks**

In [ ]:
# Split into Chunks
doc9 = nlp(u"Autonomous cars shift insurance liability toward manufacturers.")
for chunk in doc9.noun_chunks:
    print(chunk.text)

print("\n")
doc10 = nlp(u"Red cars do not carry higher insurance rates.")
for chunk in doc10.noun_chunks:
    print(chunk.text)

ValueError: ignored

**POS Tagging**

In [ ]:
doc = nlp(u"the quick brown fox jumped over the lazy dog's back.")
for token in doc:
  print(f"{token.text:{10}} {token.pos_:{10}} {token.tag_:{10}} {spacy.explain(token.tag_)}")

**Feature Extraction**

In [ ]:
# For Categorical Data
#### 1. Label/Ordinal Encoding
import pandas as pd
df = pd.DataFrame({"Country":["India","Japan","US"],"GDP":[-23,10,15]})
df

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Country'] = le.fit_transform(df['Country'])
print("Label Encoded DataFrame")
df

In [ ]:
#### 2. One Hot Encoding
dummies = pd.get_dummies(df['Country'],drop_first=True) # to avoid dummy variable trap remove once column
df_dummies = pd.concat([df,dummies],axis='columns')
df_dummies
# from sklearn.preprocessing import OneHotEncoder
# one_hot_enc = OneHotEncoder()
# one_hot_enc.fit_transform(df['Country'])

In [ ]:
#### 2. One Hot Enconding - with Keras
from keras.preprocessing.text import one_hot
from keras.preprocessing.text import text_to_word_sequence
text = "The Qucik brown fox jumped over the lazy dog."
words = text_to_word_sequence(text)
print(words)
vocab_size = len(words)
print("Vocab_size:",vocab_size)
result = one_hot(text,vocab_size)
print(result)

**CountVectorizer vs TfidfVectorizer**

=> It counts word frequency

=> TfidfVectorizer and CountVectorizer both are methods for converting text data into vectors as model can process only numerical data.

=> In CountVectorizer we only count the number of times a word appears in the document which results in biasing in favour of most frequent words. this ends up in ignoring rare words which could have helped is in processing our data more efficiently.

**Challgenes/Limitation in Count Vector**


*   Increase in size
*   Many 0's
*   no meaningful information

To overcome this , we use TfidfVectorizer .

=> In TfidfVectorizer we consider overall document weightage of a word. It helps us in dealing with most frequent words. Using it we can penalize them. TfidfVectorizer weights the word counts by a measure of how often they appear in the documents.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

cv = CountVectorizer(stop_words='english')
tv = TfidfVectorizer(stop_words='english')

messages=['Cricket Cricket Cricket Game teach us teamwork','Chess Game teach  us logic','football Game teach strength']
tv_transformed_messages = tv.fit_transform(messages)
pd.DataFrame(tv_transformed_messages.toarray(),columns = tv.get_feature_names())

chess   cricket  football  ...  strength     teach  teamwork
0  0.000000  0.917227  0.000000  ...  0.000000  0.180576  0.305742
1  0.608845  0.000000  0.000000  ...  0.000000  0.359594  0.000000
2  0.000000  0.000000  0.608845  ...  0.608845  0.359594  0.000000

[3 rows x 8 columns]

In [ ]:
# N-Grams - to find similarities between words means relation between words maintained
# it is used to auto complete like gmail
cv = CountVectorizer(ngram_range=(2,2))
messages=['Cricket Game teach us teamwork','Chess Game teach us logic','football Game teach strength']
cv_transformed_messages = cv.fit_transform(messages)
pd.DataFrame(cv_transformed_messages.toarray(),columns = cv.get_feature_names())

In [ ]:
# tfidf vectorizer
t

In [ ]:
# Word2vec : for each word, dimension are created which captures the meaning of the word.
# skip-grams : predict context words from target word
# cbow : predict target word from context words
# define tokenized senences as training data
tokenized_sentences = [['Hello','This','is','python','training','by','Aman'],
             ['Hello','This','is','Java','training','by','Aman'],
             ['Hello','This','is','Data Science','training','by','Unfold','Data','Science'],
             ['Hello','This','is','programming','training','']]

# training word2vec model
from gensim.models import Word2Vec
import warnings
warnings.filterwarnings('ignore')
mymodel_cbow = Word2Vec(tokenized_sentences, min_count=1, size = 100)
mymodel_skipgram = Word2Vec(tokenized_sentences, min_count=1, size = 100,sg=1)
# summarizing the loaded model
print(mymodel_cbow)
print(mymodel_skipgram)

Word2Vec(vocab=14, size=100, alpha=0.025)
Word2Vec(vocab=14, size=100, alpha=0.025)


In [ ]:
# summarize vocabulary
words = list(mymodel_cbow.wv.vocab)

In [ ]:
# summarize vocabulary
print(words)

['Hello', 'This', 'is', 'python', 'training', 'by', 'Aman', 'Java', 'Data Science', 'Unfold', 'Data', 'Science', 'programming', '']


In [ ]:
# access word vector for one word "training"
print(mymodel_cbow['Hello']) # here it wil print Hello word with 100 dimentions with different values for each dimention

"Bank of india"  semantic search / context search
"Bank of River"

[-3.5017885e-03 -6.6767843e-04 -5.3375436e-04 -4.7164345e-03
 -2.3350744e-03  4.8523629e-03  1.7086894e-03  2.3700360e-03
  3.1169606e-03 -3.5656586e-03  4.9215849e-03 -2.5933129e-03
  1.1365833e-03 -4.0540900e-03  2.0094363e-03  8.8771677e-04
 -3.7866542e-03  1.5079991e-03  2.8396701e-03  3.5960509e-03
  3.8333554e-03  4.8044329e-03 -1.9060089e-05 -4.5728385e-03
 -5.3578528e-04  4.3138801e-03  1.3313048e-03 -1.9220739e-03
 -8.5436093e-04 -1.0639599e-03  2.8188494e-03 -1.4518197e-03
  2.2651383e-04 -1.7388945e-03 -6.3168831e-05  3.8615144e-03
 -1.1856877e-03 -4.4560218e-03  3.6558737e-03 -2.4500065e-03
  1.3134355e-04  1.1331006e-03 -2.4853931e-03 -4.9010047e-04
  1.4711343e-03  4.7697653e-03 -1.8651837e-03  3.0319807e-03
  2.3098711e-03  3.7442821e-03  4.1510910e-03  1.0842441e-03
 -3.6488991e-04 -2.2211098e-03  2.2808870e-03  3.3509496e-03
  1.3197073e-03 -1.8747314e-05  3.5300446e-03 -4.0952112e-03
  1.3785980e-03  5.0904969e-04  1.5201821e-03  2.2016601e-04
  2.4326751e-03  1.69528

In [ ]:
print(mymodel_cbow['Hi'])

KeyError: ignored

In [ ]:
#try finding most similar words for word "Data"
mymodel_cbow.most_similar("Hi")

KeyError: ignored

In [ ]:
mymodel_cbow.similarity("python","Java")

-0.17848499

In [ ]:
#try finding most similar words for word "Data" using skip gram technique
mymodel_skipgram.most_similar("Data")

In [ ]:
mymodel_skipgram.similarity("python","Java")

In [ ]:
# check words similarity using spacy
import spacy
nlp = spacy.load('en_core_web_sm')
data = nlp(u"cat lion pet")
for token1 in data:
  for token2 in data:
    print(token1,token2,token1.similarity(token2))

**Sentiment Analysis**

VADER's `SentimentIntensityAnalyzer()` takes in a string and returns a dictionary of scores in each of four categories:
* negative
* neutral
* positive
* compound *(computed by normalizing the scores above, (i.e. aggregated score)*

In [ ]:
#using nltk
import nltk
nltk.download("vader_lexicon")

In [ ]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()
sia

In [ ]:
a = "this is a good movie ever seen"
sia.polarity_scores(a)

In [ ]:
a = "bad movie"
sia.polarity_scores(a)

# TextBlob

In [ ]:
# Spelling Correction
#!pip install textblob
#!python -m textblob.download_corpora
from textblob import TextBlob
x = "Thankks forr watching it."
TextBlob(x).correct()

In [ ]:
# tokenization
x = "Thanks#for waching this video please like it"
tokens = TextBlob(x).words
tokens

In [ ]:
# Language Translation
x = "Hello India How are you?"
print(TextBlob(x).detect_language())
print(TextBlob(x).translate(to = 'hi'))
print(TextBlob(x).translate(to = 'gu'))
print(TextBlob(x).translate(to = 'ur'))

In [ ]:
# Sentiment Analysis
from textblob.sentiments import NaiveBayesAnalyzer
x = "we all stands together. we are gonna win this fight"
TextBlob(x, analyzer = NaiveBayesAnalyzer()).sentiment

## Auto NLP


In [ ]:
!pip install autoviml

     |████████████████████████████████| 122kB 4.1MB/s 
     |████████████████████████████████| 215kB 8.2MB/s 
     |████████████████████████████████| 133kB 55.1MB/s 
     |████████████████████████████████| 133kB 46.9MB/s 
     |████████████████████████████████| 157.5MB 77kB/s 
     |████████████████████████████████| 22.3MB 1.4MB/s 
     |████████████████████████████████| 65.7MB 1.5MB/s eta 0:00:01

In [ ]:
import tensorflow_datasets as tfds
import numpy as np
import pandas as pd

In [ ]:
dataset, info = tfds.load('amazon_us_reviews/Personal_Care_Appliances_v1_00', with_info=True, batch_size=-1)
train_dataset = dataset['train']

In [ ]:
info

In [ ]:
dataset=tfds.as_numpy(train_dataset)
dataset

In [ ]:
helpful_votes=dataset['data']['helpful_votes']
review_headline=dataset['data']['review_headline']
review_body=dataset['data']['review_body']
rating=dataset['data']['star_rating']

In [ ]:
reviews_df=pd.DataFrame(np.hstack((helpful_votes[:,None],review_headline[:,None],review_body[:,None],rating[:,None])),columns=['votes','headline','reviews','rating'])

In [ ]:
convert_dict = {'votes': int,
                'headline': str,
                'reviews': str,
                'rating': int
               }

In [ ]:
reviews_df = reviews_df.astype(convert_dict)

In [ ]:
reviews_df

In [ ]:
reviews_df["target"] = reviews_df["rating"].apply(lambda x: 1 if x>= 4 else 0)

In [ ]:
reviews_df

In [ ]:
reviews_df.shape[0]

In [ ]:
reviews_df["target"].value_counts()

In [ ]:
reviews_df.info()

In [ ]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(reviews_df, test_size=0.25)

In [ ]:
from autoviml.Auto_NLP import Auto_NLP

In [ ]:
nlp_column = 'reviews'
target = 'target'
train_nlp, test_nlp, nlp_transformer, preds = Auto_NLP(
                nlp_column, train, test, target, score_type='balanced_accuracy',
                modeltype='Classification',top_num_features=50, verbose=2,
                build_model=True)

In [ ]:
nlp_transformer

In [ ]:
nlp_transformer.predict(test[nlp_column])

In [ ]:
nlp_transformer.

# BERT Vs Word2Vec

In [ ]:
!pip install flair

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 373.1/373.1 kB 4.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 788.5/788.5 kB 8.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.8/135.8 kB 7.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 18.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 26.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 5.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 48.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 19.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB

In [ ]:
import numpy as np
from flair.embeddings import WordEmbeddings
from flair.embeddings import TransformerWordEmbeddings
from flair.data import Sentence
from scipy.spatial import distance

In [ ]:
glove_embedding = WordEmbeddings('glove')

2021-02-15 14:30:19,206 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim.vectors.npy not found in cache, downloading to /tmp/tmpkkygv79p


100%|██████████| 160000128/160000128 [00:14<00:00, 11072518.26B/s]

2021-02-15 14:30:34,186 copying /tmp/tmpkkygv79p to cache at /root/.flair/embeddings/glove.gensim.vectors.npy


2021-02-15 14:30:34,483 removing temp file /tmp/tmpkkygv79p
2021-02-15 14:30:35,827 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim not found in cache, downloading to /tmp/tmpr958f413


100%|██████████| 21494764/21494764 [00:02<00:00, 7941329.81B/s]

2021-02-15 14:30:39,034 copying /tmp/tmpr958f413 to cache at /root/.flair/embeddings/glove.gensim


2021-02-15 14:30:39,066 removing temp file /tmp/tmpr958f413


Sentence1

In [ ]:
sentence_1 = Sentence('apple released iphone 12 pro max in 2020')

In [ ]:
glove_embedding.embed(sentence_1)

[Sentence: "apple released iphone 12 pro max in 2020"   [− Tokens: 8]]

In [ ]:
for token in sentence_1:
    print(token)
    print(token.embedding)
    print("\n")

Token: 1 apple
tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.0344,

In [ ]:
sentence_1[0]

Token: 1 apple

In [ ]:
sentence_1[0].embedding

tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.0344,  1.3431,  0.34

In [ ]:
sentence_1[0].embedding.shape

torch.Size([100])

Sentence 2

In [ ]:
sentence_2 = Sentence('an apple a day keeps the doctor away')

In [ ]:
glove_embedding.embed(sentence_2)

[Sentence: "an apple a day keeps the doctor away"   [− Tokens: 8]]

In [ ]:
for token in sentence_2:
    print(token)
    print(token.embedding)
    print("\n")

Token: 1 an
tensor([-0.4214, -0.1880,  0.4624, -0.1761,  0.3621,  0.3670,  0.2792,  0.1463,
        -0.0542,  0.4583,  0.0654, -0.3372,  0.0675, -0.3632,  0.5030, -0.0104,
         0.7283, -0.1756, -0.3400,  0.0729,  0.6448, -0.2391,  0.3838,  0.1386,
         1.0994, -0.2488, -0.1508, -0.4874, -0.2304,  0.0648, -0.7018,  0.8265,
         0.0613,  0.1853, -0.3016, -0.0222,  0.3430,  0.8033,  0.1714,  0.1546,
        -0.5076,  0.3957,  0.0543, -0.5308,  0.4825,  0.0862,  0.5958, -0.2238,
        -0.3955, -0.7304, -0.1028, -0.3917,  1.2290,  1.2129, -1.0365, -3.4971,
         0.1092, -1.0084,  1.9998,  0.7964,  0.3881,  0.4375,  0.0852,  0.3855,
         0.6199, -1.0320,  0.7012, -0.2246,  0.0794,  0.0913, -0.2120, -0.5543,
        -0.0534, -0.8020,  0.4680, -0.0501, -0.5742, -0.0848, -1.7227, -0.9429,
         0.9867,  0.3121, -0.3774,  0.0687, -0.7784, -0.2849,  0.8105,  0.4660,
        -0.1186, -0.9341,  0.3372,  0.0379, -0.1827, -0.0199,  0.2049, -0.4772,
        -0.4925, -0.5652,  0

In [ ]:
sentence_2[1]

Token: 2 apple

In [ ]:
sentence_2[1].embedding

tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.0344,  1.3431,  0.34

In [ ]:
sentence_2[1].embedding.shape

torch.Size([100])

Glove Distance between the same word

In [ ]:
glove_dst = distance.euclidean(np.array(sentence_1[0].embedding),
                               np.array(sentence_2[1].embedding))

In [ ]:
print("Distance between apple embeddings for Glove = {}".format(glove_dst))

Distance between apple embeddings for Glove = 0.0


Bert Embeddings

In [ ]:
bert_embedding = TransformerWordEmbeddings('bert-base-multilingual-cased')

In [ ]:
bert_embedding.embed(sentence_1)
for token in sentence_1:
    print(token)
    print(token.embedding)

Token: 1 apple
tensor([-0.5985, -0.4632,  0.1300,  ...,  1.4355,  0.0781,  0.2832])
Token: 2 released
tensor([-0.0451, -0.7260,  0.6271,  ...,  0.8646,  0.4700,  0.4862])
Token: 3 iphone
tensor([-0.3609, -0.5975,  0.5235,  ...,  0.8601,  0.1087, -0.7263])
Token: 4 12
tensor([ 0.0730,  0.1813,  0.0204,  ...,  1.0590,  0.4350, -0.1114])
Token: 5 pro
tensor([-0.2332,  0.1988, -0.2101,  ...,  1.8614,  0.7496, -0.2961])
Token: 6 max
tensor([ 0.3356,  0.1247,  0.2099,  ...,  1.3470, -0.0816,  0.4086])
Token: 7 in
tensor([ 0.0857, -0.2220,  0.1657,  ...,  1.4064, -0.2576, -0.0673])
Token: 8 2020
tensor([-0.1241,  0.3447,  0.9852,  ...,  0.8098,  1.0564, -0.2190])


In [ ]:
sentence_1[0]

Token: 1 apple

In [ ]:
sentence_1[0].embedding

tensor([-0.5985, -0.4632,  0.1300,  ...,  1.4355,  0.0781,  0.2832])

In [ ]:
sentence_1[0].embedding.shape

torch.Size([3172])

In [ ]:
bert_embedding.embed(sentence_2)

for token in sentence_2:
    print(token)
    print(token.embedding)

Token: 1 an
tensor([-0.4214, -0.1880,  0.4624,  ...,  1.2605,  0.8692,  0.1740])
Token: 2 apple
tensor([-0.5985, -0.4632,  0.1300,  ...,  1.8314,  1.0177,  0.2707])
Token: 3 a
tensor([-0.2709,  0.0440, -0.0203,  ...,  0.8354, -0.3497,  0.5959])
Token: 4 day
tensor([-0.3669,  0.4154,  0.1348,  ...,  0.9259, -0.0530,  0.1594])
Token: 5 keeps
tensor([-0.2821,  0.0814,  1.0041,  ...,  0.1253,  0.6754, -0.1647])
Token: 6 the
tensor([-0.0382, -0.2449,  0.7281,  ..., -0.1876, -0.3076,  0.5679])
Token: 7 doctor
tensor([ 0.0432, -0.4753,  0.1581,  ...,  0.7838,  0.3551,  0.3403])
Token: 8 away
tensor([-0.1038, -0.0148,  0.5993,  ...,  1.2423,  0.4363,  0.1388])


In [ ]:
sentence_2[1]

Token: 2 apple

In [ ]:
sentence_2[1].embedding

tensor([-0.5985, -0.4632,  0.1300,  ...,  1.8314,  1.0177,  0.2707])

In [ ]:
!pip install sent2vec

     |████████████████████████████████| 2.6 MB 5.2 MB/s 
     |████████████████████████████████| 3.3 MB 39.1 MB/s 
     |████████████████████████████████| 895 kB 44.5 MB/s 
     |████████████████████████████████| 636 kB 49.2 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
#### another method for BERT
from scipy import spatial
from sent2vec.vectorizer import Vectorizer

sentences = [
    "latte al cioccolato",
    "Milka  cioccolato al latte 100 g",
    "Danone, HiPRO 25g Proteine gusto cioccolato 330 ml",
]

vectorizer = Vectorizer()
vectorizer.bert(sentences)
vectors_bert = vectorizer.vectors

dist_1 = spatial.distance.cosine(vectors_bert[0], vectors_bert[1])
dist_2 = spatial.distance.cosine(vectors_bert[0], vectors_bert[2])
print('dist_1: {0}, dist_2: {1}'.format(dist_1, dist_2))
# dist_1: 0.043, dist_2: 0.192

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_transform.bias', 'vocab_layer_norm.weight', 'vocab_transform.weight', 'vocab_projector.weight', 'vocab_layer_norm.bias', 'vocab_projector.bias']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


dist_1: 0.02920389175415039, dist_2: 0.10352593660354614


# ELMO

In [ ]:
# !pip install "tensorflow>=1.7.0"
#!pip install tensorflow-hub

In [ ]:
import tensorflow_hub as hub
import tensorflow as tf

elmo = hub.load("https://tfhub.dev/google/elmo/2")

In [ ]:
# x = ["Nothing suits me like suit"] # Extract ELMo features
# embeddings = elmo(x, signature="default", as_dict=True)["elmo"]
elmo.signatures['default'](["testing", 'batch'])
elmo.shape

TypeError: ignored

# GPT-3 Clone GPT-Neo

In [ ]:
# 1. Install and Import Dependencies¶
!pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |█████████████▌                  | 834.1MB 1.9MB/s eta 0:09:50tcmalloc: large alloc 1147494400 bytes == 0x55a491942000 @  0x7f41a3a70615 0x55a4580f0cdc 0x55a4581d052a 0x55a4580f3afd 0x55a4581e4fed 0x55a458167988 0x55a4581624ae 0x55a4580f53ea 0x55a4581677f0 0x55a4581624ae 0x55a4580f53ea 0x55a45816432a 0x55a4581e5e36 0x55a458163853 0x55a4581e5e36 0x55a458163853 0x55a4581e5e36 0x55a458163853 0x55a4581e5e36 0x55a4582683e1 0x55a4581c86a9 0x55a458133cc4 0x55a4580f4559 0x55a4581684f8 0x55a4580f530a 0x55a4581633b5 0x55a4581627ad 0x55a4580f53ea 0x55a4581633b5 0x55a4580f530a 0x55a4581633b5
     |█████████████████               | 1055.7MB 1.5MB/s eta 0:10:12tcmalloc: large alloc 1434370048 bytes == 0x55a4d5f98000 @  0x7f41a3a70615 0x55a4580f0cdc 0x55a4581d052a 0x55a4580f3afd 0x55a4581e4fed 0x55a458167988 0x55a4581624ae 0x55a4580f53ea 0x55a4581677f0 0x55a4581624ae 0x55a4580f53ea 0x55a45816432a 0x55a4581e5e36 0x55a458163853 0

In [ ]:
!pip install transformers

     |████████████████████████████████| 2.5MB 8.4MB/s 
     |████████████████████████████████| 901kB 51.2MB/s 
     |████████████████████████████████| 3.3MB 50.1MB/s 


In [ ]:
from transformers import pipeline # First line

In [ ]:
# 2. Setup Generator
generator = pipeline('text-generation', model='EleutherAI/gpt-neo-2.7B') # Second line

In [ ]:
# 3. Generate Text using Prompt
prompt = "The current stock market" # Third line
res = generator(prompt, max_length=50, do_sample=True, temperature=0.9) # Fourth line

In [ ]:
# 4. Output Text
print(res[0]['generated_text'])

In [ ]:
import spacy
nlp = spacy.load('en_core_web_sm')
doc = nlp(u'The cat and the dog sleep in the basket near the door.')
for np in doc.noun_chunks:
  print(np.text)

The cat
the dog sleep
the basket
the door


In [ ]:
print(doc.noun_chunks)

In [ ]:
import spacy
nlp = spacy.load('en_core_web_sm')
doc = nlp(u'The cat and the dog sleep in the basket near the door.')
print(len([token.pos_ for token in doc if token.pos_=="NOUN"])>0)

True


In [ ]:
print("POS_:",[token.pos_ for token in doc])

POS_: ['DET', 'NOUN', 'CCONJ', 'DET', 'NOUN', 'NOUN', 'ADP', 'DET', 'NOUN', 'SCONJ', 'DET', 'NOUN', 'PUNCT']


In [ ]:
from datetime import date

today = date.today()
print("Today's date:", today)

NameError: ignored

# All Word Embedding into one

In [ ]:
# CountVectorizer
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load your dataset as a pandas DataFrame
data = pd.read_csv('your_dataset.csv')

# Split the dataset into independent and dependent variables
X = data[['numeric_column', 'text_column', 'categorical_column']]  # Independent variables
y = data['target_column']  # Dependent variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the preprocessing steps for numeric, text, and categorical columns
numeric_features = ['numeric_column']
numeric_transformer = StandardScaler()

text_features = ['text_column']
text_transformer = CountVectorizer()

categorical_features = ['categorical_column']
categorical_transformer = OneHotEncoder()

# Create the column transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('text', text_transformer, text_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Create the pipeline with preprocessing and modeling steps
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression())
])

# Fit the pipeline on the training data
pipeline.fit(X_train, y_train)

# Predict the target variable for the test data
y_pred = pipeline.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

In [ ]:
# TfidfVectorizer
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load your dataset as a pandas DataFrame
data = pd.read_csv('your_dataset.csv')

# Split the dataset into independent and dependent variables
X = data[['numeric_column', 'text_column', 'categorical_column']]  # Independent variables
y = data['target_column']  # Dependent variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the preprocessing steps for numeric, text, and categorical columns
numeric_features = ['numeric_column']
numeric_transformer = StandardScaler()

text_features = ['text_column']
text_transformer = TfidfVectorizer()

categorical_features = ['categorical_column']
categorical_transformer = OneHotEncoder()

# Create the column transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('text', text_transformer, text_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Create the pipeline with preprocessing and modeling steps
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression())
])

# Fit the pipeline on the training data
pipeline.fit(X_train, y_train)

# Predict the target variable for the test data
y_pred = pipeline.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

In [ ]:
#Word2Vec
  #If you want to use Word2Vec instead of TF-IDF vectorization for the text column, you can use the gensim library to train a Word2Vec model. Here's an example of how you can modify the code:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from gensim.models import Word2Vec
import numpy as np

# Load your dataset as a pandas DataFrame
data = pd.read_csv('your_dataset.csv')

# Split the dataset into independent and dependent variables
X = data[['numeric_column', 'text_column', 'categorical_column']]  # Independent variables
y = data['target_column']  # Dependent variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the preprocessing steps for numeric, text, and categorical columns
numeric_features = ['numeric_column']
numeric_transformer = StandardScaler()

categorical_features = ['categorical_column']
categorical_transformer = OneHotEncoder()

# Train the Word2Vec model on the text data
text_data = X_train['text_column'].values.tolist()
text_data = [text.split() for text in text_data]
word2vec_model = Word2Vec(text_data, size=100, window=5, min_count=1, workers=4)

# Function to convert text data to Word2Vec embeddings
def word2vec_transform(text_data):
    vectors = []
    for text in text_data:
        text_vector = np.zeros(100)
        count = 0
        for word in text.split():
            if word in word2vec_model.wv.vocab:
                text_vector += word2vec_model.wv[word]
                count += 1
        if count != 0:
            text_vector /= count
        vectors.append(text_vector)
    return np.array(vectors)

# Create the column transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('text', FunctionTransformer(word2vec_transform), 'text_column'),
        ('cat', categorical_transformer, categorical_features)
    ])

# Create the pipeline with preprocessing and modeling steps
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression())
])

# Fit the pipeline on the training data
pipeline.fit(X_train, y_train)

# Predict the target variable for the test data
y_pred = pipeline.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

In [ ]:
#BERT
import pandas as pd
import torch
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from transformers import BertTokenizer, BertModel
from sklearn.base import BaseEstimator, TransformerMixin


# Load your dataset as a pandas DataFrame
data = pd.read_csv('your_dataset.csv')

# Split the dataset into independent and dependent variables
X = data[['numeric_column', 'text_column', 'categorical_column']]  # Independent variables
y = data['target_column']  # Dependent variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the preprocessing steps for numeric, text, and categorical columns
numeric_features = ['numeric_column']
numeric_transformer = StandardScaler()

categorical_features = ['categorical_column']
categorical_transformer = OneHotEncoder()

# Load BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

# Custom transformer for BERT text encoding
class BertTextEncoder(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        input_ids = tokenizer.batch_encode_plus(
            X,
            add_special_tokens=True,
            padding='longest',
            truncation=True,
            return_tensors='pt'
        )['input_ids'].to(self.device)

        with torch.no_grad():
            outputs = model(input_ids)[0][:, 0, :].cpu().numpy()

        return outputs

# Create the column transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('text', BertTextEncoder(), 'text_column'),
        ('cat', categorical_transformer, categorical_features)
    ])

# Create the pipeline with preprocessing and modeling steps
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression())
])

# Fit the pipeline on the training data
pipeline.fit(X_train, y_train)

# Predict the target variable for the test data
y_pred = pipeline.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

In [ ]:
#ELMO
  ###To use ELMo embeddings for the text column instead of TfidfVectorizer, you'll need to utilize a pre-trained ELMo model and the tensorflow library. Here's an example of how you can modify the code:
import pandas as pd
import tensorflow as tf
import tensorflow_hub as hub
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load your dataset as a pandas DataFrame
data = pd.read_csv('your_dataset.csv')

# Split the dataset into independent and dependent variables
X = data[['numeric_column', 'text_column', 'categorical_column']]  # Independent variables
y = data['target_column']  # Dependent variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Load the pre-trained ELMo model
elmo = hub.load("https://tfhub.dev/google/elmo/3")

# Define the preprocessing steps for numeric, text, and categorical columns
numeric_features = ['numeric_column']
numeric_transformer = StandardScaler()

categorical_features = ['categorical_column']
categorical_transformer = OneHotEncoder()

# Define a custom transformer for the text column using ELMo
class ElmoTransformer:
    def __init__(self, model):
        self.model = model

    def transform(self, X):
        embeddings = tf.squeeze(self.model.signatures["default"](tf.constant(X)))
        return embeddings.numpy()

    def fit(self, X, y=None):
        pass

# Create the column transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('text', ElmoTransformer(elmo), 'text_column'),
        ('cat', categorical_transformer, categorical_features)
    ])

# Create the pipeline with preprocessing and modeling steps
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression())
])

# Fit the pipeline on the training data
pipeline.fit(X_train, y_train)

# Predict the target variable for the test data
y_pred = pipeline.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')


In [ ]:
#FastText
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
import fasttext
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load your dataset as a pandas DataFrame
data = pd.read_csv('your_dataset.csv')

# Split the dataset into independent and dependent variables
X = data[['numeric_column', 'text_column', 'categorical_column']]  # Independent variables
y = data['target_column']  # Dependent variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the preprocessing steps for numeric, text, and categorical columns
numeric_features = ['numeric_column']
numeric_transformer = StandardScaler()

text_features = ['text_column']

categorical_features = ['categorical_column']
categorical_transformer = OneHotEncoder()

# Create the column transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features),
        ('text', 'passthrough', text_features)
    ])

# Create the pipeline with preprocessing and modeling steps
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression())
])

# Fit the pipeline on the training data
pipeline.fit(X_train, y_train)

# Preprocess the text column using FastText and obtain text embeddings
X_train_text = pipeline.named_steps['preprocessor'].transformers_[2][1].transform(X_train[text_features])
X_test_text = pipeline.named_steps['preprocessor'].transformers_[2][1].transform(X_test[text_features])

# Train FastText model on the training text data
model = fasttext.train_unsupervised(X_train_text, model='skipgram')

# Convert text data to embeddings
X_train_text_emb = [model.get_sentence_vector(text) for text in X_train_text]
X_test_text_emb = [model.get_sentence_vector(text) for text in X_test_text]

# Combine the preprocessed numeric, categorical, and text embeddings
X_train_combined = pd.concat([pd.DataFrame(X_train[numeric_features].values),
                              pd.DataFrame(X_train_text_emb),
                              pd.DataFrame(X_train[categorical_features].values)], axis=1)

X_test_combined = pd.concat([pd.DataFrame(X_test[numeric_features].values),
                             pd.DataFrame(X_test_text_emb),
                             pd.DataFrame(X_test[categorical_features].values)], axis=1)

# Fit the classifier on the combined data
pipeline.named_steps['classifier'].fit(X_train_combined, y_train)

# Predict the target variable for the test data
y_pred = pipeline.named_steps['classifier'].predict(X_test_combined)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')


In [ ]:
#GPT-3
import pandas as pd
import openai
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Set up your OpenAI API credentials
openai.api_key = 'YOUR_API_KEY'

# Load your dataset as a pandas DataFrame
data = pd.read_csv('your_dataset.csv')

# Split the dataset into independent and dependent variables
X = data[['numeric_column', 'text_column', 'categorical_column']]  # Independent variables
y = data['target_column']  # Dependent variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the preprocessing steps for numeric, text, and categorical columns
numeric_features = ['numeric_column']
numeric_transformer = StandardScaler()

categorical_features = ['categorical_column']
categorical_transformer = OneHotEncoder()

# Create the GPT-3 text encoder function
def gpt3_encoder(text):
    response = openai.Completion.create(
        engine='davinci-codex',
        prompt=text,
        max_tokens=100,
        n=1,
        stop=None,
        temperature=0.7
    )
    return response.choices[0].text.strip()

# Create the column transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('text', FunctionTransformer(gpt3_encoder), 'text_column'),  # Use gpt3_encoder function
        ('cat', categorical_transformer, categorical_features)
    ])

# Create the pipeline with preprocessing and modeling steps
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression())
])

# Fit the pipeline on the training data
pipeline.fit(X_train, y_train)

# Predict the target variable for the test data
y_pred = pipeline.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

# Custom Names Entity Recognition Custom-(NER)
Building Custom Named Entity Recognition Model Using Spacy



In [ ]:
import spacy
!python -m spacy download en_core_web_lg

2023-08-28 17:40:38.803556: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.7/587.7 MB 1.0 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')


In [ ]:
nlp = spacy.load("en_core_web_lg")
nlp

In [ ]:
doc = nlp("Donad Trump was President of USA")
doc

Donad Trump was President of USA

In [ ]:
type(doc)

spacy.tokens.doc.Doc

In [ ]:
doc.ents

(Donad Trump, USA)

In [ ]:
doc.ents[0], type(doc.ents[0])

(Donad Trump, spacy.tokens.span.Span)

In [ ]:
from spacy import displacy
displacy.render(doc, style="ent", jupyter=True)

In [ ]:
import json
# https://www.kaggle.com/datasets/finalepoch/medical-ner
with open('/content/drive/MyDrive/Colab Notebooks/Datasets/Corona2.json', 'r') as f:
    data = json.load(f)

In [ ]:
data['examples'][0]

{'id': '18c2f619-f102-452f-ab81-d26f7e283ffe',
 'content': "While bismuth compounds (Pepto-Bismol) decreased the number of bowel movements in those with travelers' diarrhea, they do not decrease the length of illness.[91] Anti-motility agents like loperamide are also effective at reducing the number of stools but not the duration of disease.[8] These agents should be used only if bloody diarrhea is not present.[92]\n\nDiosmectite, a natural aluminomagnesium silicate clay, is effective in alleviating symptoms of acute diarrhea in children,[93] and also has some effects in chronic functional diarrhea, radiation-induced diarrhea, and chemotherapy-induced diarrhea.[45] Another absorbent agent used for the treatment of mild diarrhea is kaopectate.\n\nRacecadotril an antisecretory medication may be used to treat diarrhea in children and adults.[86] It has better tolerability than loperamide, as it causes less constipation and flatulence.[94]",
 'metadata': {},
 'annotations': [{'id': '0825a1

In [ ]:
data['examples'][0].keys()

dict_keys(['id', 'content', 'metadata', 'annotations', 'classifications'])

In [ ]:
data['examples'][0]['content']

"While bismuth compounds (Pepto-Bismol) decreased the number of bowel movements in those with travelers' diarrhea, they do not decrease the length of illness.[91] Anti-motility agents like loperamide are also effective at reducing the number of stools but not the duration of disease.[8] These agents should be used only if bloody diarrhea is not present.[92]\n\nDiosmectite, a natural aluminomagnesium silicate clay, is effective in alleviating symptoms of acute diarrhea in children,[93] and also has some effects in chronic functional diarrhea, radiation-induced diarrhea, and chemotherapy-induced diarrhea.[45] Another absorbent agent used for the treatment of mild diarrhea is kaopectate.\n\nRacecadotril an antisecretory medication may be used to treat diarrhea in children and adults.[86] It has better tolerability than loperamide, as it causes less constipation and flatulence.[94]"

In [ ]:
data['examples'][0]['annotations'][0]

{'id': '0825a1bf-6a6e-4fa2-be77-8d104701eaed',
 'tag_id': 'c06bd022-6ded-44a5-8d90-f17685bb85a1',
 'end': 371,
 'start': 360,
 'example_id': '18c2f619-f102-452f-ab81-d26f7e283ffe',
 'tag_name': 'Medicine',
 'value': 'Diosmectite',
 'correct': None,
 'human_annotations': [{'timestamp': '2020-03-21T00:24:32.098000Z',
   'annotator_id': 1,
   'tagged_token_id': '0825a1bf-6a6e-4fa2-be77-8d104701eaed',
   'name': 'Ashpat123',
   'reason': 'exploration'}],
 'model_annotations': []}

In [ ]:
training_data = []
for example in data['examples']:
  temp_dict = {}
  temp_dict['text'] = example['content']
  temp_dict['entities'] = []
  for annotation in example['annotations']:
    start = annotation['start']
    end = annotation['end']
    label = annotation['tag_name'].upper()
    temp_dict['entities'].append((start, end, label))
  training_data.append(temp_dict)

print(training_data[0])

{'text': "While bismuth compounds (Pepto-Bismol) decreased the number of bowel movements in those with travelers' diarrhea, they do not decrease the length of illness.[91] Anti-motility agents like loperamide are also effective at reducing the number of stools but not the duration of disease.[8] These agents should be used only if bloody diarrhea is not present.[92]\n\nDiosmectite, a natural aluminomagnesium silicate clay, is effective in alleviating symptoms of acute diarrhea in children,[93] and also has some effects in chronic functional diarrhea, radiation-induced diarrhea, and chemotherapy-induced diarrhea.[45] Another absorbent agent used for the treatment of mild diarrhea is kaopectate.\n\nRacecadotril an antisecretory medication may be used to treat diarrhea in children and adults.[86] It has better tolerability than loperamide, as it causes less constipation and flatulence.[94]", 'entities': [(360, 371, 'MEDICINE'), (383, 408, 'MEDICINE'), (104, 112, 'MEDICALCONDITION'), (679,

In [ ]:
training_data[0]['text']

"While bismuth compounds (Pepto-Bismol) decreased the number of bowel movements in those with travelers' diarrhea, they do not decrease the length of illness.[91] Anti-motility agents like loperamide are also effective at reducing the number of stools but not the duration of disease.[8] These agents should be used only if bloody diarrhea is not present.[92]\n\nDiosmectite, a natural aluminomagnesium silicate clay, is effective in alleviating symptoms of acute diarrhea in children,[93] and also has some effects in chronic functional diarrhea, radiation-induced diarrhea, and chemotherapy-induced diarrhea.[45] Another absorbent agent used for the treatment of mild diarrhea is kaopectate.\n\nRacecadotril an antisecretory medication may be used to treat diarrhea in children and adults.[86] It has better tolerability than loperamide, as it causes less constipation and flatulence.[94]"

In [ ]:
training_data[0]['entities']

[(360, 371, 'MEDICINE'),
 (383, 408, 'MEDICINE'),
 (104, 112, 'MEDICALCONDITION'),
 (679, 689, 'MEDICINE'),
 (6, 23, 'MEDICINE'),
 (25, 37, 'MEDICINE'),
 (461, 470, 'MEDICALCONDITION'),
 (577, 589, 'MEDICINE'),
 (853, 865, 'MEDICALCONDITION'),
 (188, 198, 'MEDICINE'),
 (754, 762, 'MEDICALCONDITION'),
 (870, 880, 'MEDICALCONDITION'),
 (823, 833, 'MEDICINE'),
 (852, 853, 'MEDICALCONDITION'),
 (461, 469, 'MEDICALCONDITION'),
 (535, 543, 'MEDICALCONDITION'),
 (692, 704, 'MEDICINE'),
 (563, 571, 'MEDICALCONDITION')]

In [ ]:
training_data[0]['text'][360:371]

'Diosmectite'

In [ ]:
from spacy.tokens import DocBin
from tqdm import tqdm

nlp = spacy.blank("en") # load a new spacy model
doc_bin = DocBin()

In [ ]:
from spacy.util import filter_spans

for training_example  in tqdm(training_data):
    text = training_example['text']
    labels = training_example['entities']
    doc = nlp.make_doc(text)
    ents = []
    for start, end, label in labels:
        span = doc.char_span(start, end, label=label, alignment_mode="contract")
        if span is None:
            print("Skipping entity")
        else:
            ents.append(span)
    filtered_ents = filter_spans(ents)
    doc.ents = filtered_ents
    doc_bin.add(doc)

doc_bin.to_disk("train.spacy")

 26%|██▌       | 8/31 [00:00<00:00, 72.53it/s]

Skipping entity
Skipping entity
Skipping entity
Skipping entity
Skipping entity
Skipping entity
Skipping entity
Skipping entity
Skipping entity
Skipping entity
Skipping entity
Skipping entity
Skipping entity
Skipping entity
Skipping entity
Skipping entity


100%|██████████| 31/31 [00:00<00:00, 131.64it/s]


In [ ]:
!python -m spacy init fill-config base_config.cfg config.cfg

2023-08-28 17:51:50.406240: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Usage: python -m spacy init fill-config 
           [OPTIONS] BASE_PATH [OUTPUT_FILE]
Try 'python -m spacy init fill-config --help' for help.
╭─ Error ──────────────────────────────────────────────────────────────────────╮
│ Invalid value for 'BASE_PATH': File 'base_config.cfg' does not exist.        │
╰──────────────────────────────────────────────────────────────────────────────╯


In [ ]:
!python -m spacy train config.cfg --output ./ --paths.train ./train.spacy --paths.dev ./train.spacy

2023-08-28 17:52:02.886320: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Usage: python -m spacy train [OPTIONS] CONFIG_PATH
Try 'python -m spacy train --help' for help.
╭─ Error ──────────────────────────────────────────────────────────────────────╮
│ Invalid value for 'CONFIG_PATH': Path 'config.cfg' does not exist.           │
╰──────────────────────────────────────────────────────────────────────────────╯


In [ ]:
nlp_ner = spacy.load("model-best")

OSError: ignored

In [ ]:
doc = nlp_ner("While bismuth compounds (Pepto-Bismol) decreased the number of bowel movements in those with travelers' diarrhea, they do not decrease the length of illness.[91] Anti-motility agents like loperamide are also effective at reducing the number of stools but not the duration of disease.[8] These agents should be used only if bloody diarrhea is not present.")

colors = {"PATHOGEN": "#F67DE3", "MEDICINE": "#7DF6D9", "MEDICALCONDITION":"#a6e22d"}
options = {"colors": colors}

spacy.displacy.render(doc, style="ent", options= options, jupyter=True)

NameError: ignored